### ISSUE TITLE
Crash when hitting Ctrl+Z directly after Ctrl+T

### ISSUE THREAD

**Issue by zolrath** [Pullusb/Box_deform#1]
Hello, love the tool, thanks a lot for making it!

I have a reproducible crash to report:

  1. Create a New 2D Project.
  2. Ensure Box Deform is an enabled Add-on.
  3. Draw a simple stroke using the default pencil.
  4. Hit `Ctrl+T`
  5. Hit `Ctrl+Z`
  6. Blender immediately crashes to desktop.

Appears to happen with either deform type.
This is using Blender 2.83 LTS on Windows 10.

**Comment by Pullusb** [comment]
Thank you for the report, I'll try to fix this.

**Comment by Pullusb** [comment]
Ok @zolrath the problem is bigger than expected and lead to a choice.

Every modal I checked just disable `ctrl+Z` during execution. And talking about it on python devs forums seems to return the same answer : the proper way is to do without undos.
Still being able to undo lattices move is and increase in usability (over stability).

So I'd like to ask, are you ok with no ctrl+Z during lattice transform or do you use it a lot ?

Either way I'll look a bit further to see if I can hack a solution, but this seems limited by the API access to undo stack...
In the end If I can't find a fix I think I'll disable it.  
I can't let a big crash like this happen.

**Comment by Pullusb** [comment]
Fixed, Ctrl+Z is now disabled in 0.2.4 (Undo during modal generate weird behavior and can cause other errors/crashes)
